name: Rust Build

on:
  push:
    branches-ignore:
      - main
  pull_request:
    types:
      [opened, reopened, synchronize]
      
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
